# Generated by Django 2.1.1 on 2018-10-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('spotify_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Spotify_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('following_user_id', models.BigIntegerField()),
                ('follower_user_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('spotify_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('player_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('displayname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('salt', models.CharField(max_length=10)),
                ('icon', models.ImageField(null=True, upload_to='')),
                ('current_listening_track', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
