# Generated by Django 2.1.1 on 2018-11-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battari', '0003_auto_20181107_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(max_length=100),
        ),
    ]
