# Generated by Django 2.1.1 on 2018-11-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battari', '0006_auto_20181109_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebase_token',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='user',
            name='spotify_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
