# Generated by Django 2.1.1 on 2018-11-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battari', '0008_remove_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower_user_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following_user_id',
            field=models.CharField(max_length=30),
        ),
    ]
