# Generated by Django 2.1.1 on 2018-11-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battari', '0009_auto_20181130_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='receive_user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='useraction',
            old_name='user_id',
            new_name='user',
        ),
    ]
